### ISSUE TITLE
Supporting newer versions

### ISSUE THREAD

**Issue by kburns** [conda-forge/julia-feedstock#81] opened 2020-01-21 17:10 UTC
Thanks for everyone's work towards making Julia available via conda!  It looks like there are some changes to the Julia build system post 1.1 that are preventing this conda build from succeeding (see #74,  #78. and #80).  I just wanted to check if there looks to be a quick fix to anyone more experienced with building Julia than myself, before I dig into the details.

**Comment by mariusvniekerk** [comment] 2020-02-21 02:54
I'd say try combining #76 with some of the newer versions?

**Comment by osbornejr** [comment] 2020-05-15 07:30
As a complete novice to conda-forge feedstocks, I have been trying to look into this a bit. From the [Azure pipeline output](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=157338&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c) (as generated by #82) it gets stuck during the system build bootstrapping process. I get the same result when I build the feedstock recipe locally (using the provided python script). This still occurs even if I remove the relevant line in `recipes/build.sh` to prevent the issue resolved in #76 from being an issue.   

In the [Julia github build docs](https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#required-build-tools-and-external-libraries) they note that 

> Over time, the base library may accumulate enough changes such that the bootstrapping process in building the system image will fail.

The solution is to run `make clean && make` or `make cleanall`.  Interestingly, if I grab the source tarball from the `build-artifacts/` directory, I can extract that and build it with plain `make` no problems. 

Is there some way to force the `conda-smithy` docker image to run `make cleanall` and see if that fixes things? I can't see how the `make` command is executed in the auto-generated `.scripts/build_steps.sh` file, and imagine that it is occuring as part of the more general feedstock  process. 

N.B. although I don't think the issue resolved in #76 is the direct cause of this problem, it was (via #14) what originally motivated me to investigate this issue. It seems at v1.1.1 Julia was in a transitional phase towards using `DEPOT_PATH`, and [several nice features](https://docs.julialang.org/en/latest/manual/environment-variables/#JULIA_HISTORY-1) related to it mentioned in their documentation now do not work as stated (I'm aware they've probably been updated since v1.1.1 release). These _do_ work in v1.4.1, and (I think) would allow quite a neat partitioning of Julia environments per conda environment, whilst avoiding multiple package installation locations. To try that out though, I really need to be able to install v1.4.1 via conda-forge.

**Comment by osbornejr** [comment] 2020-05-15 09:38
Have now worked out that this is all controlled in `recipes/build.sh` (obviously!), but changing to various configurations `make clean` did nothing. However, I noticed that every time I was building locally, it was failing at `pcre_h.jl`. Disabling `USE_SYSTEM_PCRE` in `recipes/build.sh` allowed v1.4.1 to build! 

Unfortunately it went on to fail one of the `Pkg/pkg` tests, which also happened when I tried to build the existing v1.1.1 Julia locally. I note that that it passing fine on Azure, so I'll do a PR and see how it fares.

**Comment by osbornejr** [comment] 2020-05-19 02:05
I realised from reading through other issues that getting all dependencies via conda-forge is desired and that this workaround is probably not a solution. But at least hopefully this might someone who knows what they are doing some time (i.e. the PCRE package dependency is what is stalling the builds).

**Comment by innovate-invent** [comment] 2020-06-22 20:50
https://github.com/conda-forge/julia-feedstock/pull/90 successfully builds for linux, someone familiar with OSX will have to fix the OSX release.

**Comment by thompsonmj** [comment] 2021-05-20 15:54
#102 seems to be echo this plea to have an up-to-date version of Julia available through conda-forge. I would like to use virtual environments for reproducibility, but the Julia environment vs conda environment chicken and egg dilemma is complicating this. Anyway, I don't know how to update this so Julia 1.6+ can work in conda, so I'm resurrecting this issue to add a request that this be updated and maintained 🙂

**Closed** 2021-08-10 07:52 UTC
